server:
  port: 8888
spring:
  application:
    name: config
#  cloud:
#    config:
#      uri: https://github.com/fanwencong/Spring-config-server.git
eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
      serviceUrl:
        defaultZone: http://localhost:8671/eureka/
